[ ] use "{SilkDir}Common\CMN_Ocxlib.inc"
[ ] 
[+] window MainWin wARSetup
	[ ] tag "AR Setup*[1]"
	[+] Menu File
		[ ] tag "File"
		[+] Menu New
			[ ] tag "New"
			[+] MenuItem GroupingRules
				[ ] tag "Grouping Rules"
			[+] MenuItem PriceSchedules
				[ ] tag "Price Schedules"
			[+] MenuItem SystemPriceSchedules
				[ ] tag "System Price Schedules"
			[+] MenuItem Procedures
				[ ] tag "Procedures"
			[+] MenuItem Groups
				[ ] tag "Groups"
			[+] MenuItem CompositeBilling
				[ ] tag "Composite Billing"
			[+] MenuItem OverlappingComponents
				[ ] tag "Overlapping Components"
			[+] MenuItem DiagnosisCPT
				[ ] tag "Diagnosis CPT"
			[+] MenuItem DiagnosisType
				[ ] tag "Diagnosis Type"
			[+] MenuItem ABNModifier
				[ ] tag "ABN Modifier"
			[+] MenuItem Discount
				[ ] tag "Discount"
			[+] MenuItem PayorRedirection
				[ ] tag "Payor Redirection"
			[+] MenuItem CCI
				[ ] tag "CCI"
			[+] Menu Collections
				[ ] tag "Collections"
				[+] MenuItem Activity
					[ ] tag "Activity"
				[+] MenuItem ActivityOutcome
					[ ] tag "Activity Outcome"
			[+] MenuItem TransactionTypes
				[ ] tag "Transaction Types"
			[+] MenuItem PatientTypes
				[ ] tag "Patient Types"
			[+] MenuItem Clients
				[ ] tag "Clients"
			[+] MenuItem Insurances
				[ ] tag "Insurances"
			[+] MenuItem Facilities
				[ ] tag "Facilities"
			[+] MenuItem Departments
				[ ] tag "Departments"
			[+] MenuItem WorkstationAssignment
				[ ] tag "Workstation Assignment"
			[+] MenuItem BillingEntities
				[ ] tag "Billing Entities"
			[+] MenuItem Salesperson
				[ ] tag "Salesperson"
			[+] MenuItem CommissionProfile
				[ ] tag "Commission Profile"
			[+] MenuItem Commissions
				[ ] tag "Commissions"
			[+] MenuItem Doctors
				[ ] tag "Doctors"
			[+] Menu Dictionaries
				[ ] tag "Dictionaries"
				[+] MenuItem CPTCodes
					[ ] tag "CPT Codes"
				[+] MenuItem DenialCodes
					[ ] tag "Denial Codes"
				[+] MenuItem ICD9Codes
					[ ] tag "ICD9 Codes"
				[+] MenuItem FinancialClass
					[ ] tag "Financial Class"
				[+] MenuItem Modifiers
					[ ] tag "Modifiers"
				[+] MenuItem RevenueCodes
					[ ] tag "Revenue Codes"
				[+] MenuItem ServicePlaces
					[ ] tag "Service Places"
				[+] MenuItem ServiceTypes
					[ ] tag "Service Types"
				[+] MenuItem Specialties
					[ ] tag "Specialties"
				[+] MenuItem TransactionClass
					[ ] tag "Transaction Class"
				[+] MenuItem ZipRanges
					[ ] tag "Zip Ranges"
				[+] MenuItem Wards
					[ ] tag "Wards"
			[+] Menu Actions
				[ ] tag "Actions"
				[+] MenuItem ActionToInform
					[ ] tag "Action To Inform"
				[+] MenuItem ActionToPerform
					[ ] tag "Action To Perform"
				[+] MenuItem Errors
					[ ] tag "Errors"
				[+] MenuItem Exceptions
					[ ] tag "Exceptions"
				[+] MenuItem Messages
					[ ] tag "Messages"
			[+] Menu GLSetup
				[ ] tag "GL Setup"
				[+] MenuItem DataFields
					[ ] tag "Data Fields"
				[+] MenuItem DataMap
					[ ] tag "Data Map"
				[+] MenuItem TransactionMap
					[ ] tag "Transaction Map"
				[+] MenuItem JournalRecord
					[ ] tag "Journal Record"
				[+] MenuItem JournalFields
					[ ] tag "Journal Fields"
			[+] MenuItem RuleBasedSystem
				[ ] tag "Rule Based System"
			[+] MenuItem TagDefinition
				[ ] tag "Tag Definition"
			[+] MenuItem HL7Translation
				[ ] tag "HL7 Translation"
			[+] MenuItem VisitAlterationSetup
				[ ] tag "Visit Alteration Setup"
			[+] MenuItem SystemParameters
				[ ] tag "System Parameters"
		[+] Menu Open
			[ ] tag "Open"
			[+] MenuItem GroupingRules
				[ ] tag "Grouping Rules"
			[+] MenuItem PriceSchedules
				[ ] tag "Price Schedules"
			[+] MenuItem SystemPriceSchedules
				[ ] tag "System Price Schedules"
			[+] MenuItem Procedures
				[ ] tag "Procedures"
			[+] MenuItem Groups
				[ ] tag "Groups"
			[+] MenuItem CompositeBilling
				[ ] tag "Composite Billing"
			[+] MenuItem OverlappingComponents
				[ ] tag "Overlapping Components"
			[+] MenuItem DiagnosisCPT
				[ ] tag "Diagnosis CPT"
			[+] MenuItem DiagnosisType
				[ ] tag "Diagnosis Type"
			[+] MenuItem ABNModifier
				[ ] tag "ABN Modifier"
			[+] MenuItem Discount
				[ ] tag "Discount"
			[+] MenuItem PayorRedirection
				[ ] tag "Payor Redirection"
			[+] MenuItem CCI
				[ ] tag "CCI"
			[+] Menu Collections
				[ ] tag "Collections"
				[+] MenuItem Activity
					[ ] tag "Activity"
				[+] MenuItem ActivityOutcome
					[ ] tag "Activity Outcome"
			[+] MenuItem TransactionTypes
				[ ] tag "Transaction Types"
			[+] MenuItem PatientTypes
				[ ] tag "Patient Types"
			[+] MenuItem Clients
				[ ] tag "Clients"
			[+] MenuItem Insurances
				[ ] tag "Insurances"
			[+] MenuItem Facilities
				[ ] tag "Facilities"
			[+] MenuItem Departments
				[ ] tag "Departments"
			[+] MenuItem WorkstationAssignment
				[ ] tag "Workstation Assignment"
			[+] MenuItem BillingEntities
				[ ] tag "Billing Entities"
			[+] MenuItem Salesperson
				[ ] tag "Salesperson"
			[+] MenuItem CommissionProfile
				[ ] tag "Commission Profile"
			[+] MenuItem Commissions
				[ ] tag "Commissions"
			[+] MenuItem Doctors
				[ ] tag "Doctors"
			[+] Menu Dictionaries
				[ ] tag "Dictionaries"
				[+] MenuItem CPTCodes
					[ ] tag "CPT Codes"
				[+] MenuItem DenialCodes
					[ ] tag "Denial Codes"
				[+] MenuItem ICD9Codes
					[ ] tag "ICD9 Codes"
				[+] MenuItem FinancialClass
					[ ] tag "Financial Class"
				[+] MenuItem Modifiers
					[ ] tag "Modifiers"
				[+] MenuItem RevenueCodes
					[ ] tag "Revenue Codes"
				[+] MenuItem ServicePlaces
					[ ] tag "Service Places"
				[+] MenuItem ServiceTypes
					[ ] tag "Service Types"
				[+] MenuItem Specialties
					[ ] tag "Specialties"
				[+] MenuItem TransactionClass
					[ ] tag "Transaction Class"
				[+] MenuItem ZipRanges
					[ ] tag "Zip Ranges"
				[+] MenuItem Wards
					[ ] tag "Wards"
			[+] Menu Actions
				[ ] tag "Actions"
				[+] MenuItem ActionToInform
					[ ] tag "Action To Inform"
				[+] MenuItem ActionToPerform
					[ ] tag "Action To Perform"
				[+] MenuItem Errors
					[ ] tag "Errors"
				[+] MenuItem Exceptions
					[ ] tag "Exceptions"
				[+] MenuItem Messages
					[ ] tag "Messages"
			[+] Menu GLSetup
				[ ] tag "GL Setup"
				[+] MenuItem DataFields
					[ ] tag "Data Fields"
				[+] MenuItem DataMap
					[ ] tag "Data Map"
				[+] MenuItem TransactionMap
					[ ] tag "Transaction Map"
				[+] MenuItem JournalRecord
					[ ] tag "Journal Record"
				[+] MenuItem JournalFields
					[ ] tag "Journal Fields"
			[+] MenuItem RuleBasedSystem
				[ ] tag "Rule Based System"
			[+] MenuItem TagDefinition
				[ ] tag "Tag Definition"
			[+] MenuItem HL7Translation
				[ ] tag "HL7 Translation"
			[+] MenuItem VisitAlterationSetup
				[ ] tag "Visit Alteration Setup"
			[+] MenuItem SystemParameters
				[ ] tag "System Parameters"
		[+] MenuItem Save
			[ ] tag "Save"
		[+] MenuItem Close
			[ ] tag "Close"
		[+] MenuItem InitDatabase
			[ ] tag "Init database"
		[+] Menu LoadCodes
			[ ] tag "Load Codes"
			[+] MenuItem CPT
				[ ] tag "CPT"
			[+] MenuItem CPTDIAG
				[ ] tag "CPT-DIAG"
			[+] MenuItem ICD9
				[ ] tag "ICD9"
			[+] MenuItem Modifier
				[ ] tag "Modifier"
			[+] MenuItem Denial
				[ ] tag "Denial"
			[+] MenuItem ServicePlace
				[ ] tag "Service Place"
			[+] MenuItem CCI
				[ ] tag "CCI"
		[+] MenuItem CreateAcceptableFeeSchedule
			[ ] tag "Create Acceptable Fee Schedule"
		[+] MenuItem BulkPriceChange
			[ ] tag "Bulk Price Change"
		[+] MenuItem PrintPreview
			[ ] tag "Print Preview"
		[+] MenuItem Print
			[ ] tag "Print"
		[+] MenuItem UserPrivileges
			[ ] tag "User privileges"
		[+] MenuItem Exit
			[ ] tag "Exit"
	[+] Menu Edit
		[ ] tag "Edit"
		[+] MenuItem Cut
			[ ] tag "Cut"
		[+] MenuItem Copy
			[ ] tag "Copy"
		[+] MenuItem Paste
			[ ] tag "Paste"
		[+] MenuItem Delete
			[ ] tag "Delete"
	[+] Menu View
		[ ] tag "View"
		[+] MenuItem Toolbar
			[ ] tag "Toolbar"
		[+] MenuItem StatusBar
			[ ] tag "Status Bar"
		[+] MenuItem ShowHistory
			[ ] tag "Show History"
	[+] Menu Record
		[ ] tag "Record"
		[+] MenuItem FirstRecord
			[ ] tag "First record"
		[+] MenuItem PreviousRecord
			[ ] tag "Previous Record"
		[+] MenuItem NextRecord
			[ ] tag "Next Record"
		[+] MenuItem LastRecord
			[ ] tag "Last Record"
		[+] MenuItem GoToRecord
			[ ] tag "Go to record"
		[+] MenuItem BrowseRecords
			[ ] tag "Browse records"
		[+] Menu Filter
			[ ] tag "Filter"
			[+] MenuItem Payor
				[ ] tag "Payor"
			[+] MenuItem ProvNum
				[ ] tag "Prov Num"
			[+] MenuItem Facility
				[ ] tag "Facility"
			[+] MenuItem CPT
				[ ] tag "CPT"
			[+] MenuItem Diagnosis
				[ ] tag "Diagnosis"
			[+] MenuItem Type
				[ ] tag "Type"
			[+] MenuItem None
				[ ] tag "None"
		[+] Menu Find
			[ ] tag "Find"
			[+] MenuItem Payor
				[ ] tag "Payor"
			[+] MenuItem ProvNum
				[ ] tag "Prov Num"
			[+] MenuItem Facility
				[ ] tag "Facility"
			[+] MenuItem CPT
				[ ] tag "CPT"
			[+] MenuItem Diagnosis
				[ ] tag "Diagnosis"
			[+] MenuItem Type
				[ ] tag "Type"
		[+] MenuItem FindNext
			[ ] tag "Find Next"
		[+] Menu Sort
			[ ] tag "Sort"
			[+] MenuItem Payor
				[ ] tag "Payor"
			[+] MenuItem ProvNum
				[ ] tag "Prov Num"
			[+] MenuItem Facility
				[ ] tag "Facility"
			[+] MenuItem CPT
				[ ] tag "CPT"
			[+] MenuItem Diagnosis
				[ ] tag "Diagnosis"
			[+] MenuItem Type
				[ ] tag "Type"
		[+] MenuItem EditRecord
			[ ] tag "Edit Record"
		[+] MenuItem UndoChanges
			[ ] tag "Undo changes"
		[+] MenuItem DuplicateRecord
			[ ] tag "Duplicate Record"
		[+] MenuItem AuditTrail
			[ ] tag "Audit Trail"
		[+] MenuItem CustomFields
			[ ] tag "Custom Fields"
		[+] MenuItem ShowComments
			[ ] tag "Show Comments"
		[+] MenuItem OpenLink
			[ ] tag "Open Link"
	[+] Menu Tools
		[ ] tag "Tools"
		[+] MenuItem SendSetupUpdateToLAB
			[ ] tag "Send setup update to LAB"
		[+] MenuItem CheckDiagCPTRestrictions
			[ ] tag "Check Diag-CPT restrictions"
		[+] MenuItem Options
			[ ] tag "Options"
		[+] MenuItem CachingServer
			[ ] tag "Caching Server"
		[+] MenuItem CheckPriceRestrictions
			[ ] tag "Check Price restrictions"
		[+] MenuItem Duplicate
			[ ] tag "Duplicate"
		[+] MenuItem CalculateTestPrice
			[ ] tag "Calculate Test Price"
		[+] MenuItem TestFormulary
			[ ] tag "Test Formulary"
		[+] Menu FileBuild
			[ ] tag "File Build"
			[+] MenuItem Tests
				[ ] tag "Tests"
			[+] MenuItem Doctors
				[ ] tag "Doctors"
			[+] MenuItem Wards
				[ ] tag "Wards"
			[+] MenuItem GrpTst
				[ ] tag "GrpTst"
			[+] MenuItem BillRules
				[ ] tag "BillRules"
			[+] MenuItem Departments
				[ ] tag "Departments"
			[+] MenuItem WrkDepFclty
				[ ] tag "WrkDepFclty"
		[+] MenuItem ValidationUtility
			[ ] tag "Validation Utility"
		[+] MenuItem Spelling
			[ ] tag "Spelling....."
	[+] Menu xWindow
		[ ] tag "Window"
		[+] MenuItem Cascade
			[ ] tag "Cascade"
		[+] MenuItem TileHorizontally
			[ ] tag "Tile Horizontally"
		[+] MenuItem TileVertically
			[ ] tag "Tile Vertically"
		[+] MenuItem ArrangeIcons
			[ ] tag "Arrange Icons"
	[+] Menu Help
		[ ] tag "Help"
		[+] MenuItem Help
			[ ] tag "Help"
		[+] MenuItem AboutARSetup
			[ ] tag "About AR Setup"
[ ] 
[+] window ChildWin wDoctor
	[ ] tag "DOCTOR:*[1]"
	[ ] parent wARSetup
	[ ] 
	[ ] STRING sPrefix = "[DialogBox]$59648"		
	[ ] 
	[ ] 
	[+] TextField edtCode
		[ ] tag "{sPrefix}/Code:"
	[+] TextField edtDoctorSecondID
		[ ] tag "{sPrefix}/Second ID:"
	[+] TextField edtDoctorThirdID
		[ ] tag "{sPrefix}/Third ID:"
	[+] CheckBoxEx cbActive
		[ ] tag "{sPrefix}/Active"
	[+] OLEGEditMy edtNPI
		[ ] tag "{sPrefix}/NPI:"
	[+] TextField edtUPIN
		[ ] tag "{sPrefix}/UPIN:"
	[+] TextField edtTitle
		[ ] tag "{sPrefix}/Title"
	[+] TextField edtLastName
		[ ] tag "{sPrefix}/Last Name"
	[+] TextField edtFirstName
		[ ] tag "{sPrefix}/First Name"
	[+] TextField edtMiddleName
		[ ] tag "{sPrefix}/Middle Name"
	[+] TextField edtSuffix
		[ ] tag "{sPrefix}/Suffix"
	[+] OLEGEditMy edtSS1
		[ ] tag "{sPrefix}/SS#:"
	[+] OLEGComb lstType					
		[ ] tag "{sPrefix}/Type:"
	[+] TextField edtSpecialty
		[ ] tag "{sPrefix}/Specialty:"
	[+] PushButtonEx btnLOOKUP1
		[ ] tag "{sPrefix}/LOOKUP[1]"
	[+] TextField edtMedSrvCode
		[ ] tag "{sPrefix}/Med Srv Code:"
	[+] TextField edtLicence
		[ ] tag "{sPrefix}/[TextField]#12"
	[ ] 
	[+] TextField edtStreet1
		[ ] tag "{sPrefix}/Street1:"
	[+] TextField edtStreet2
		[ ] tag "{sPrefix}/Street2:|[DialogBox]$0/Street2:"
	[+] OLEGEditMy edtCity
		[ ] tag "{sPrefix}/City:|[DialogBox]$0/City:"
	[+] OLEGComb lstState					
		[ ] tag "{sPrefix}/State:|[DialogBox]$0/State:"
	[+] OLEGEditMy edtZip1
		[ ] tag "{sPrefix}/Zip:[1]|[DialogBox]$0/Zip:[1]"
	[+] OLEGEditMy edtCountry
		[ ] tag "{sPrefix}/[OLEGEdit]#5|[DialogBox]$0/[OLEGEdit]#5"
	[+] TextField edtPhone1
		[ ] tag "{sPrefix}/Phone:[1]|[DialogBox]$0/Phone:[1]"
	[+] OLEGEditMy edtExt1
		[ ] tag "{sPrefix}/Ext.:[1]|[DialogBox]$0/Ext.:[1]"
	[+] PushButtonEx btnPushButton2
		[ ] tag "{sPrefix}/^Ext.:[1]|[DialogBox]$0/^Ext.:[1]"
	[+] TextField edtPhone2
		[ ] tag "{sPrefix}/Phone:[2]|[DialogBox]$0/Phone:[2]"
	[+] OLEGEditMy edtExt2
		[ ] tag "{sPrefix}/Ext.:[2]|[DialogBox]$0/Ext.:[2]"
	[+] PushButtonEx btnPushButton3
		[ ] tag "{sPrefix}/^Ext.:[2]|[DialogBox]$0/^Ext.:[2]"
	[+] OLEGGrid gridProviderNumbers
		[ ] tag "{sPrefix}/Provider Numbers:"
	[+] TextField edtPager
		[ ] tag "{sPrefix}/Pager:"
	[+] TextField edtModem
		[ ] tag "{sPrefix}/Modem:"
	[+] TextField edtFax
		[ ] tag "{sPrefix}/Fax:"
	[+] TextField edtTerritory
		[ ] tag "{sPrefix}/Territory:"
	[+] PushButtonEx btnLOOKUP2
		[ ] tag "{sPrefix}/LOOKUP[2]"
	[+] TextField edtContact
		[ ] tag "{sPrefix}/Contact:"
	[+] TextField edtRegion
		[ ] tag "{sPrefix}/Region:"
	[+] PushButtonEx btnLOOKUP3
		[ ] tag "{sPrefix}/LOOKUP[3]"
	[+] OLEGEditMy edtEMail
		[ ] tag "{sPrefix}/E-mail:"
	[+] TextField edtCounty
		[ ] tag "{sPrefix}/County:"
	[+] PushButtonEx btnLOOKUP4
		[ ] tag "{sPrefix}/LOOKUP[4]"
	[+] PushButtonEx btnWards
		[ ] tag "{sPrefix}/Wards"
	[+] PushButtonEx btnPrices
		[ ] tag "{sPrefix}/Prices"
[ ] 
[ ] // *********** Окна для F2
[+] window DialogBox wF2Search
	[ ] tag "[DialogBox]*[1]"
	[ ] parent wARSetup
	[+] PushButtonEx btnSearch
		[ ] tag "Search"
	[+] PopupList lstQuaeryLimit
		[ ] tag "[PopupList]*[1]"
	[+] PushButtonEx btnMore
		[ ] tag "More"
	[+] PushButtonEx btnCancel
		[ ] tag "Cancel"
	[+] DialogBox Facility2
		[ ] tag "Facility"
		[+] TextField edtCode
			[ ] tag "Code"
		[+] TextField edtName
			[ ] tag "Name"
		[+] TextField edtCLIA
			[ ] tag "CLIA #"
		[+] TextField edtBillingEntity
			[ ] tag "Billing Entity"
		[+] TextField edtPlaceOfService
			[ ] tag "Place of Service"
		[+] TextField edtTypeOfService
			[ ] tag "Type of Service"
		[+] TextField edtNPI
			[ ] tag "NPI #"
[+] window DialogBox wButtonOk
	[ ] tag "[DialogBox]*[1]"
	[ ] parent wF2Search
	[+] PushButtonEx btnOK
		[ ] tag "OK"
		[ ] 
[+] window DialogBox wSearch
	[ ] tag "[DialogBox]*[1]"
	[ ] parent wARSetup
	[+] OLEGGrid GridSearch
		[ ] tag "#1"
	[+] PushButtonEx btnOK
		[ ] tag "OK"
	[+] PushButtonEx btnBack
		[ ] tag "Back"
	[+] PushButtonEx btnCancel
		[ ] tag "Cancel"
	[+] PushButtonEx btnPrint
		[ ] tag "Print"
[ ] 
[ ] 
[ ] 
[ ] // *********** Функции проверки введенного значения и его длины в TextField и OLEGEdit
[+] winclass TextField: TextField
	[ ] //******* Ф-я проверки верности ввода тестовой строки и ее длины в текст-филд
	[+] void SetTextWithVerify (INT iMax)
		[ ] STRING sVerifyStr = RandStr("X({iMax+1})")
		[ ] this.SetText(sVerifyStr)
		[+] if ( !((StrPos(this.GetText(),sVerifyStr) == 1) || (StrPos(this.GetText(),Upper(sVerifyStr)) == 1)) )
			[ ] print("########## --------> Failed String in {this}")
		[+] if ( !(len(this.GetText()) == iMax) )
			[ ] print("########## --------> Failed Length in field {this}")
		[ ] 
	[ ] 
	[ ] //******* Ф-я проверки верности ввода строки цифр и ее длины в текст-филд
	[+] void SetIntWithVerify (INT iMax)
		[ ] STRING sVerifyStr = RandStr("9({iMax+1})")
		[ ] this.SetText(sVerifyStr)
		[+] if ( !(StrPos(this.GetText(),sVerifyStr) == 1) )
			[ ] print("########## --------> Failed String in {this}")
		[+] if ( !(len(this.GetText()) == iMax) )
			[ ] print("########## --------> Failed Length in field {this}")
	[ ] 
	[ ] 
[+] winclass OLEGEditMy: OLEGEdit
	[ ] //******* Ф-я проверки верности ввода тестовой строки и ее длины в текст-филд
	[+] void SetTextWithVerify (INT iMax)
		[ ] STRING sVerifyStr = RandStr("X({iMax+1})")
		[ ] this.SetText(sVerifyStr)
		[+] if ( !((StrPos(this.sDataString,sVerifyStr) == 1) || (StrPos(this.sDataString,Upper(sVerifyStr)) == 1)) )
			[ ] print("########## --------> Failed String in {this}")
		[+] if ( !(len(this.sDataString) == iMax) )
			[ ] print("########## --------> Failed Length in field {this}")
		[ ] 
	[ ] 
	[ ] //******* Ф-я проверки верности ввода строки цифр и ее длины в текст-филд
	[+] void SetIntWithVerify (INT iMax)
		[ ] STRING sVerifyStr = RandStr("9({iMax+1})")
		[ ] this.SetText(sVerifyStr)
		[+] if ( !(StrPos(this.sDataString,sVerifyStr) == 1) )
			[ ] print("########## --------> Failed String in {this}")
		[+] if ( !(len(this.sDataString) == iMax) )
			[ ] print("########## --------> Failed Length in field {this}")
			[ ] 
	[ ] 
	[ ] 
	[ ] //******* Не доделана! Ф-я проверки верности ввода строки символов + строки цифр и их длин в текст-филд
	[+] // void SetTextIntWithVerify (INT iMaxStr, INT iMaxInt)
		[ ] // 
		[ ] // STRING sStr = RandStr("X({iMaxStr+1})") 
		[ ] // STRING sInt = RandStr("9({iMaxStr+1})") 
		[ ] // STRING sVerifyStr = sStr + sInt 
		[ ] // 
		[ ] // 
		[ ] // this.SetText(sVerifyStr)
		[ ] // 
		[ ] // 
		[+] // if ( !((StrPos(this.sDataString,sVerifyStr) == 1) || (StrPos(this.sDataString,Upper(sVerifyStr)) == 1)) )
			[ ] // print("########## --------> Failed String in {this}")
			[ ] // 
			[ ] // 
			[ ] // 
			[ ] // 
		[+] // if ( !(len(this.sDataString) == (iMaxStr + iMaxInt) ) )
			[ ] // print("########## --------> Failed Length in field {this}")
		[ ] // 
[ ] 
